export const global_game_options = {
    bypass_protection: false,
    fade_out_palette: false,
    use_tile_data: false,
    use_text_cutscenes: false,
    use_seq_cutscenes: true,
    use_words_protection: false,
    use_white_tshirt: false,
    play_asc_cutscene: false,
    play_caillou_cutscene: false,
    play_metro_cutscene: false,
    play_serrure_cutscene: false,
    play_carte_cutscene: false,
    play_gamesaved_sound: false,
}