const UINT8_MAX = 0xFF
const UINT16_MAX = 0xFFFF
const SCREENBLOCK_W = 8
const SCREENBLOCK_H = 8
const GAMESCREEN_W = 256
const GAMESCREEN_H = 224
const CHAR_W = 8
const CHAR_H = 8
const kIngameSaveSlot = 0
const kRewindSize = 120 // 10mins (~2MB)
const kAutoSaveSlot = UINT8_MAX
const kAutoSaveIntervalMs = 5 * 1000

const CT_ROOM_SIZE = 0x40
const CT_UP_ROOM = 0x00
const CT_DOWN_ROOM = 0x40
const CT_RIGHT_ROOM = 0x80
const CT_LEFT_ROOM = 0xC0

const PGE_NUM = 256
const PGE_FLAG_MIRRORED = 0x01
const PGE_FLAG_FLIP_X = 0x02
const PGE_FLAG_ACTIVE = 0x04
const PGE_FLAG_SPECIAL_ANIM = 0x08

const INIT_PGE_FLAG_HAS_COLLISION = 0x01
const INIT_PGE_FLAG_UNKNOWN_BIT_1 = 0x02
const INIT_PGE_FLAG_IN_CURRENT_ROOM_LIST = 0x04
const INIT_PGE_INIT_FLAGS_HAS_FLAG_3 = 0x08

const OBJ_FLAG_TOGGLE_MIRROR = 0x01
const OBJ_FLAG_DEC_LIFE = 0x02
const OBJ_FLAG_INC_LIFE = 0x04
const OBJ_FLAG_SET_DEAD = 0x08

export {
  UINT8_MAX,
  UINT16_MAX,
  SCREENBLOCK_W,
  SCREENBLOCK_H,
  GAMESCREEN_W,
  GAMESCREEN_H,
  CHAR_W,
  CHAR_H,
  kIngameSaveSlot,
  kRewindSize,
  kAutoSaveSlot,
  kAutoSaveIntervalMs,
  CT_ROOM_SIZE,
  CT_UP_ROOM,
  CT_DOWN_ROOM,
  CT_RIGHT_ROOM,
  CT_LEFT_ROOM,
  PGE_NUM,
  PGE_FLAG_MIRRORED,
  PGE_FLAG_FLIP_X,
  PGE_FLAG_ACTIVE,
  PGE_FLAG_SPECIAL_ANIM,
  INIT_PGE_FLAG_HAS_COLLISION,
  INIT_PGE_FLAG_UNKNOWN_BIT_1,
  INIT_PGE_FLAG_IN_CURRENT_ROOM_LIST,
  INIT_PGE_INIT_FLAGS_HAS_FLAG_3,
  OBJ_FLAG_TOGGLE_MIRROR,
  OBJ_FLAG_DEC_LIFE,
  OBJ_FLAG_INC_LIFE,
  OBJ_FLAG_SET_DEAD,
}
