const UINT8_MAX = 0xFF
const PGE_FLAG_MIRRORED = 0x01
const PGE_FLAG_FLIP_X = 0x02
const PGE_FLAG_ACTIVE = 0x04
const PGE_FLAG_SPECIAL_ANIM = 0x08

const INIT_PGE_FLAG_HAS_COLLISION = 0x01
const INIT_PGE_FLAG_UNKNOWN_BIT_1 = 0x02
const INIT_PGE_FLAG_IN_CURRENT_ROOM_LIST = 0x04
const INIT_PGE_INIT_FLAGS_HAS_FLAG_3 = 0x08

const OBJ_FLAG_TOGGLE_MIRROR = 0x01
const OBJ_FLAG_DEC_LIFE = 0x02
const OBJ_FLAG_INC_LIFE = 0x04
const OBJ_FLAG_SET_DEAD = 0x08

export {
  UINT8_MAX,
  PGE_FLAG_MIRRORED,
  PGE_FLAG_FLIP_X,
  PGE_FLAG_ACTIVE,
  PGE_FLAG_SPECIAL_ANIM,
  INIT_PGE_FLAG_HAS_COLLISION,
  INIT_PGE_FLAG_UNKNOWN_BIT_1,
  INIT_PGE_FLAG_IN_CURRENT_ROOM_LIST,
  INIT_PGE_INIT_FLAGS_HAS_FLAG_3,
  OBJ_FLAG_TOGGLE_MIRROR,
  OBJ_FLAG_DEC_LIFE,
  OBJ_FLAG_INC_LIFE,
  OBJ_FLAG_SET_DEAD,
}
